CREATE TABLE Usuarios (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    Apellidos VARCHAR(100) NOT NULL,
    Mail VARCHAR(255) NOT NULL,
    Username VARCHAR(255) UNIQUE NOT NULL,
    Pass VARCHAR(255) NOT NULL
);

CREATE TABLE Videos (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Titulo VARCHAR(100) NOT NULL,
    Autor INT NOT NULL,
    Fecha_Creacion DATE NOT NULL,
    Duracion TIME NOT NULL,
    Reproducciones INT NOT NULL DEFAULT 0,
    Descripcion VARCHAR(1024),
    Formato VARCHAR(5),
    URL VARCHAR(1024),
    FOREIGN KEY (Autor) REFERENCES Usuarios(ID) ON DELETE CASCADE
);